Upgrade Apple IIgs builds

diff --git a/Makefile.apple2gs b/Makefile.apple2gs
--- a/Makefile.apple2gs
+++ b/Makefile.apple2gs
@@ -9,7 +9,10 @@
 
 # Space or comma separated list of cc65 supported target platforms to build for.
 # Default: c64 (lowercase!)
-TARGETS := apple2gs
+TARGETS := apple2
+FUJINET_LIB_VERSION = 4.7.0
+FUJINET_LIB = fujinet-lib
+FUJINET_LIB_VERSION_DIR = $(FUJINET_LIB)/$(FUJINET_LIB_VERSION)-$(TARGETS)
 
 # Name of the final, single-file executable.
 # Default: name of the current dir with target name appended
@@ -27,11 +30,11 @@ CONFIG  :=
 
 # Additional C compiler flags and options.
 # Default: none
-CFLAGS = -I -P +F cc=-p\"src:apple2:orcac.h\" cc=-isrc cc=-isrc:apple2 cc=-i13:cc65 cc=-dBUILD_APPLE2 cc=-d__APPLE2__ cc=-d__fastcall__=
+CFLAGS = -I -P +F cc=-p\"src:apple2:orcac.h\" cc=-isrc cc=-isrc:apple2 cc=-i13:cc65 cc=-ifujinet-lib cc=-dBUILD_APPLE2 cc=-d__APPLE2__ cc=-d__fastcall__=
 
 # Additional assembler flags and options.
 # Default: none
-ASFLAGS =
+ASFLAGS = -P
 
 # Additional linker flags and options.
 # Default: none
@@ -209,23 +212,27 @@ TARGETLIST := $(subst $(COMMA),$(SPACE),$(TARGETS))
 
 ifeq ($(words $(TARGETLIST)),1)
 
+#FUJINET_LIB_DOWNLOAD_URL = https://github.com/FujiNetWIFI/fujinet-lib/releases/download/v$(FUJINET_LIB_VERSION)/fujinet-lib-$(TARGETLIST)-$(FUJINET_LIB_VERSION).zip
+#FUJINET_LIB_DOWNLOAD_FILE = $(FUJINET_LIB)/fujinet-lib-$(TARGETLIST)-$(FUJINET_LIB_VERSION).zip
+FUJINET_LIB_DOWNLOAD_URL = https://github.com/FujiNetWIFI/fujinet-lib/releases/download/v$(FUJINET_LIB_VERSION)/fujinet-lib-apple2gs-$(FUJINET_LIB_VERSION).zip
+FUJINET_LIB_DOWNLOAD_FILE = $(FUJINET_LIB)/fujinet-lib-apple2gs-$(FUJINET_LIB_VERSION).zip
+
 # Set PROGRAM to something like 'myprog.c64'.
 override PROGRAM := $(PROGRAM)
 
 # Set SOURCES to something like 'src/foo.c src/bar.s'.
 # Use of assembler files with names ending differently than .s is deprecated!
 SOURCES := $(wildcard $(SRCDIR)/*.c)
-SOURCES += $(wildcard $(SRCDIR)/*.s)
+#SOURCES += $(wildcard $(SRCDIR)/*.s)
 SOURCES += $(wildcard $(SRCDIR)/*.asm)
-SOURCES += $(wildcard $(SRCDIR)/*.a65)
+#SOURCES += $(wildcard $(SRCDIR)/*.a65)
 
 # Add to SOURCES something like 'src/c64/me.c src/c64/too.s'.
 # Use of assembler files with names ending differently than .s is deprecated!
 SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.c)
-SOURCES += $(wildcard $(SRCDIR)/apple2/*.c)
-SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.s)
+#SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.s)
 SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.asm)
-SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.a65)
+#SOURCES += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.a65)
 
 # Set OBJECTS to something like 'obj/c64/foo.o obj/c64/bar.o'.
 OBJECTS := $(addsuffix .root,$(basename $(addprefix $(TARGETOBJDIR)/,$(notdir $(SOURCES)))))
@@ -236,6 +243,8 @@ DEPENDS := $(OBJECTS:.root=.d)
 # Add to LIBS something like 'src/foo.lib src/c64/bar.lib'.
 LIBS += $(wildcard $(SRCDIR)/*.lib)
 LIBS += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.lib)
+#LIBS += $(FUJINET_LIB_VERSION_DIR)/fujinet-$(TARGETLIST)-$(FUJINET_LIB_VERSION).lib
+LIBS += $(FUJINET_LIB_VERSION_DIR)/fujinet-apple2gs-$(FUJINET_LIB_VERSION).lib
 
 # Add to CONFIG something like 'src/c64/bar.cfg src/foo.cfg'.
 CONFIG += $(wildcard $(SRCDIR)/$(TARGETLIST)/*.cfg)
@@ -247,10 +256,13 @@ ifneq ($(word 2,$(CONFIG)),)
   $(info Using config file $(CONFIG) for linking)
 endif
 
-.SUFFIXES:
-.PHONY: all test clean zap love
+#ASFLAGS += --asm-include-dir src/$(TARGETLIST)/asminc --asm-include-dir $(FUJINET_LIB_VERSION_DIR)
+CFLAGS += cc=-i$(FUJINET_LIB_VERSION_DIR) cc=-dUSING_FUJINET_LIB
 
-all: $(PROGRAM)
+.SUFFIXES:
+.PHONY: all test clean get_fujinet_lib zap love
+
+all: get_fujinet_lib $(PROGRAM)
 
 -include $(DEPENDS)
 -include $(STATEFILE)
@@ -285,6 +297,26 @@ $(foreach o,$(subst $(COMMA),$(SPACE),$(OPTIONS)),$(eval $(_$o_)))
 # Strip potential variant suffix from the actual cc65 target.
 CC65TARGET := $(firstword $(subst .,$(SPACE),$(TARGETLIST)))
 
+get_fujinet_lib:
+	@if [ ! -f "$(FUJINET_LIB_DOWNLOAD_FILE)" ]; then \
+		if [ -d "$(FUJINET_LIB_VERSION_DIR)" ]; then \
+		  echo "A directory already exists with version $(FUJINET_LIB_VERSION) - please remove it first"; \
+			exit 1; \
+		fi; \
+		HTTPSTATUS=$$(curl -Is $(FUJINET_LIB_DOWNLOAD_URL) | head -n 1 | awk '{print $$2}'); \
+		if [ "$${HTTPSTATUS}" == "404" ]; then \
+			echo "ERROR: Unable to find file $(FUJINET_LIB_DOWNLOAD_URL)"; \
+			exit 1; \
+		fi; \
+		echo "Downloading fujinet-lib for $(TARGETLIST) version $(FUJINET_LIB_VERSION) from $(FUJINET_LIB_DOWNLOAD_URL)"; \
+		mkdir -p $(FUJINET_LIB); \
+		curl -L $(FUJINET_LIB_DOWNLOAD_URL) -o $(FUJINET_LIB_DOWNLOAD_FILE); \
+		echo "Unzipping to $(FUJINET_LIB)"; \
+		unzip -o $(FUJINET_LIB_DOWNLOAD_FILE) -d $(FUJINET_LIB_VERSION_DIR); \
+		iix chtyp -t lib $(FUJINET_LIB_VERSION_DIR)/fujinet-apple2gs-$(FUJINET_LIB_VERSION).lib; \
+		echo "Unzip complete."; \
+	fi
+
 # The remaining targets.
 $(TARGETOBJDIR):
 	$(call MKDIR,$@)
@@ -292,7 +324,7 @@ $(TARGETOBJDIR):
 vpath %.c $(SRCDIR)/apple2 $(SRCDIR)/$(TARGETLIST) $(SRCDIR)
 
 $(TARGETOBJDIR)/%.root: %.c | $(TARGETOBJDIR)
-	$(CC) $< $(CFLAGS) keep=$(TARGETOBJDIR)/$$
+	$(CC) $(CFLAGS) $< keep=$(TARGETOBJDIR)/$$
 
 vpath %.s $(SRCDIR)/$(TARGETLIST) $(SRCDIR)
 
@@ -302,7 +334,7 @@ $(TARGETOBJDIR)/%.root: %.s | $(TARGETOBJDIR)
 vpath %.asm $(SRCDIR)/$(TARGETLIST) $(SRCDIR)
 
 $(TARGETOBJDIR)/%.root: %.asm | $(TARGETOBJDIR)
-	$(CC) -t $(CC65TARGET) -c --create-dep $(@:.o=.d) $(ASFLAGS) -o $@ $<
+	$(CC) $(ASFLAGS) $< keep=$(subst .root,,$@)
 
 vpath %.a65 $(SRCDIR)/$(TARGETLIST) $(SRCDIR)
 
@@ -321,6 +353,12 @@ dist: $(PROGRAM)
 	cp dist.apple2/bootable.po dist.apple2/dist.po
 	./dist.apple2/add-file.sh dist.apple2/dist.po config config exe
 #	cp dist.apple2/dist.po ../fujinet-platformio/data/webui/device_specific/BUILD_APPLE/autorun.po
+gendebug: $(PROGRAM)
+	@echo "Generating debug.scr script for AppleWin"
+	@echo 'echo "Loading symbols"' > debug.scr
+	@awk '{printf("sym %s = %s\n", substr($$3, 2), $$2)}' < $(PROGRAM).lbl >> debug.scr
+	@echo 'bpx _main' >> debug.scr
+	@echo 'bpx _fuji_close_directory' >> debug.scr
 
 clean:
 	$(call RMFILES,$(OBJECTS))
@@ -328,6 +366,7 @@ clean:
 	$(call RMFILES,$(REMOVES))
 	$(call RMFILES,$(PROGRAM))
 	$(call RMFILES,*.map)
+	rm -rf dist/
 
 else # $(words $(TARGETLIST)),1
 
