[apple2] Change to use fujinet-lib over local IO functions
Moved all io functions to use fuji_ functions from fujinet-lib.
This has also removed all the inline asm sp_ functions :tada:

diff --git a/Makefile.atari b/Makefile.atari
--- a/Makefile.atari
+++ b/Makefile.atari
@@ -11,9 +11,9 @@
 # Default: c64 (lowercase!)
 TARGETS := atari
 
-FUJINET_LIB_VERSION = 3.0.0
+FUJINET_LIB_VERSION = 3.0.1
 FUJINET_LIB = fujinet-lib
-FUJINET_LIB_VERSION_DIR = $(FUJINET_LIB)/$(FUJINET_LIB_VERSION)
+FUJINET_LIB_VERSION_DIR = $(FUJINET_LIB)/$(FUJINET_LIB_VERSION)-$(TARGETS)
 
 # Name of the final, single-file executable.
 # Default: name of the current dir with target name appended
@@ -280,7 +280,7 @@ ifneq ($(word 2,$(CONFIG)),)
   $(info Using config file $(CONFIG) for linking)
 endif
 
-ASFLAGS += --asm-include-dir src/atari/asminc --asm-include-dir $(FUJINET_LIB_VERSION_DIR)
+ASFLAGS += --asm-include-dir src/$(TARGETLIST)/asminc --asm-include-dir $(FUJINET_LIB_VERSION_DIR)
 CFLAGS += --include-dir $(FUJINET_LIB_VERSION_DIR) -DUSING_FUJINET_LIB
 
 .SUFFIXES:
@@ -327,7 +327,12 @@ get_fujinet_lib:
 		  echo "A directory already exists with version $(FUJINET_LIB_VERSION) - please remove it first"; \
 			exit 1; \
 		fi; \
-		echo "Downloading fujinet-lib for $(TARGETLIST) version $(FUJINET_LIB_VERSION)"; \
+		HTTPSTATUS=$$(curl -Is $(FUJINET_LIB_DOWNLOAD_URL) | head -n 1 | awk '{print $$2}'); \
+		if [ "$${HTTPSTATUS}" == "404" ]; then \
+			echo "ERROR: Unable to find file $(FUJINET_LIB_DOWNLOAD_URL)"; \
+			exit 1; \
+		fi; \
+		echo "Downloading fujinet-lib for $(TARGETLIST) version $(FUJINET_LIB_VERSION) from $(FUJINET_LIB_DOWNLOAD_URL)"; \
 		mkdir -p $(FUJINET_LIB); \
 		curl -L $(FUJINET_LIB_DOWNLOAD_URL) -o $(FUJINET_LIB_DOWNLOAD_FILE); \
 		echo "Unzipping to $(FUJINET_LIB)"; \
